version: '3.8'

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nizamuddin@513
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    expose:
      - "5432"

  mongo:
    image: mongo
    expose:
      - "27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    expose:
      - "2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - "9092"

  auth-service:
    build: ./apps/backend/services/auth-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Nizamuddin@513
      DB_NAME: postgres
      JWT_ACCESS_SECRET: 897o867i5eursxcgvghiji0i43q4a
      JWT_REFRESH_SECRET: ytyrts1234545687908uihghcxzx
    depends_on:
      - postgres
    expose:
      - "4001"

  user-service:
    build: ./apps/backend/services/user-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Nizamuddin@513
      DB_NAME: postgres
      JWT_ACCESS_SECRET: 897o867i5eursxcgvghiji0i43q4a
    depends_on:
      - postgres
    expose:
      - "4002"

  restaurant-service:
    build: ./apps/backend/services/restaurant-service
    environment:
      MONGO_URI: mongodb://mongo:27017/restaurant_db
      JWT_ACCESS_SECRET: 897o867i5eursxcgvghiji0i43q4a
    depends_on:
      - mongo
    expose:
      - "4003"

  order-service:
    build: ./apps/backend/services/order-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Nizamuddin@513
      DB_NAME: postgres
      RESTAURANT_SERVICE: http://restaurant-service:4003
      JWT_ACCESS_SECRET: 897o867i5eursxcgvghiji0i43q4a
    depends_on:
      - postgres
      - kafka
    expose:
      - "4004"

  payment-service:
    build: ./apps/backend/services/payment-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Nizamuddin@513
      DB_NAME: postgres
      ORDER_SERVICE: http://order-service:4004
      JWT_ACCESS_SECRET: 897o867i5eursxcgvghiji0i43q4a
    depends_on:
      - postgres
      - kafka
    expose:
      - "4005"

  api-gateway:
    build: ./apps/backend/api-gateway
    environment:
      PORT: "4000"
      AUTH_SERVICE: http://auth-service:4001
      USER_SERVICE: http://user-service:4002
      RESTAURANT_SERVICE: http://restaurant-service:4003
      ORDER_SERVICE: http://order-service:4004
      PAYMENT_SERVICE: http://payment-service:4005
    depends_on:
      - auth-service
      - user-service
      - restaurant-service
      - order-service
      - payment-service
    ports:
      - "4000:4000"

volumes:
  postgres_data: