apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: nizamuddin1n/payment-service:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "Nizamuddin@513"
            - name: DB_NAME
              value: "postgres"
            - name: ORDER_SERVICE
              value: "http://order-service:4004"
            - name: JWT_ACCESS_SECRET
              value: "897o867i5eursxcgvghiji0i43q4a"
            - name: KAFKA_BROKER
              value: "kafka:9092"
          ports:
            - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 4005
      targetPort: 4005