apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: nizamuddin1n/restaurant-service:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/restaurant_db"
            - name: JWT_ACCESS_SECRET
              value: "897o867i5eursxcgvghiji0i43q4a"
            - name: REDIS_HOST
              value: "redis"
          ports:
            - containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-service
  ports:
    - port: 4003
      targetPort: 4003